version: '2'
services:
  dev:
    image: "dev:zephyr"
    build:
      context: "."
      dockerfile: ./dev/Dockerfile
      args:
        # Update 'VARIANT' to pick a Python version: 3, 3.12
        VARIANT: "3.12"
        # Update 'CMAKE_VERSION' to pick a specific version of CMake: 3.20.5, 3.21.1, 4.0.3
        CMAKE_VERSION: "3.20.5"
    volumes:
      - ..:/home/vscode/dev/zephyrproject:cached
      - ./dev/.vscode:/home/vscode/dev/.vscode:cached
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    tty: true
    command: bash
